# define prune ratios for your network
# # 5.4x (weight sparsity)
prune_ratios:
  module.conv1.weight:
    0
  module.layer1.0.conv1.weight:
    0.5
  module.layer1.0.conv2.weight:
    0.5
  module.layer1.0.conv3.weight:
    0.7
  module.layer1.0.shortcut.0.weight:
    0.7
  module.layer1.1.conv1.weight:
    0.7
  module.layer1.1.conv2.weight:
    0.75
  module.layer1.1.conv3.weight:
    0.75
  module.layer1.2.conv1.weight:
    0.75
  module.layer1.2.conv2.weight:
    0.75
  module.layer1.2.conv3.weight:
    0.75
  module.layer2.0.conv1.weight:
    0.75
  module.layer2.0.conv2.weight:
    0.75
  module.layer2.0.conv3.weight:
    0.75
  module.layer2.0.shortcut.0.weight:
    0.75
  module.layer2.1.conv1.weight:
    0.8
  module.layer2.1.conv2.weight:
    0.8
  module.layer2.1.conv3.weight:
    0.8
  module.layer2.2.conv1.weight:
    0.85
  module.layer2.2.conv2.weight:
    0.85
  module.layer2.2.conv3.weight:
    0.85
  module.layer2.3.conv1.weight:
    0.86
  module.layer2.3.conv2.weight:
    0.88
  module.layer2.3.conv3.weight:
    0.88
  module.layer3.0.conv1.weight:
    0.88
  module.layer3.0.conv2.weight:
    0.88
  module.layer3.0.conv3.weight:
    0.88
  module.layer3.0.shortcut.0.weight:
    0.88
  module.layer3.1.conv1.weight:
    0.88
  module.layer3.1.conv2.weight:
    0.85
  module.layer3.1.conv3.weight:
    0.8
  module.layer3.2.conv1.weight:
    0.8
  module.layer3.2.conv2.weight:
    0.8
  module.layer3.2.conv3.weight:
    0.8
  module.layer3.3.conv1.weight:
    0.8
  module.layer3.3.conv2.weight:
    0.8
  module.layer3.3.conv3.weight:
    0.8
  module.layer3.4.conv1.weight:
    0.8
  module.layer3.4.conv2.weight:
    0.8
  module.layer3.4.conv3.weight:
    0.8
  module.layer3.5.conv1.weight:
    0.8
  module.layer3.5.conv2.weight:
    0.8
  module.layer3.5.conv3.weight:
    0.82
  module.layer4.0.conv1.weight:
    0.82
  module.layer4.0.conv2.weight:
    0.85
  module.layer4.0.conv3.weight:
    0.85
  module.layer4.0.shortcut.0.weight:
    0.85
  module.layer4.1.conv1.weight:
    0.8
  module.layer4.1.conv2.weight:
    0.8
  module.layer4.1.conv3.weight:
    0.8
  module.layer4.2.conv1.weight:
    0.8
  module.layer4.2.conv2.weight:
    0.8
  module.layer4.2.conv3.weight:
    0.7

